title: Henry-WK
logo: https://github.com/Henry-WK/henry-wk.github.io/assets/152219380/7f632b5e-4a1f-4f87-81b0-3378f4e2258d
description: Undergraduate at UMASS Amherst. Studying: Computer Science, Biology, Math, and Ethical Research
theme: jekyll-theme-minimal
show_downloads: false

url: https://henry-wk.github.io/
